when:
  - event: [push, manual]

workspace:
  base: /main
  path: src

steps:
  - name: build
    image: pfillion/dind
    commands:
      - make build
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock

  - name: test
    image: pfillion/dind
    commands:
      - make test
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock

  - name: docker-push
    image: pfillion/dind
    environment:
      DOCKER_USERNAME:
        from_secret: docker_username
      DOCKER_PASSWORD:
        from_secret: docker_password
    commands:
      - make docker-push
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      - evaluate: 'MODE_LOCAL != "true"'